# Generated by Django 4.2 on 2023-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='experience',
            field=models.CharField(max_length=400),
        ),
    ]
